### ISSUE TITLE
TypeError: this.client.executeWebhook is not a function

### ISSUE THREAD

**Issue by enrique4r** [Khaaz/AxonCore#86]
The next error code is displayed on console after running the start script:

```bash
yarn run v1.21.1
$ node -r esm src/index.js
  ___                  _____                
 / _ \                /  __ \               
/ /_\ __  _____  _ __ | /  \/ ___  _ __ ___ 
|  _  \ \/ / _ \| '_ \| |    / _ \| '__/ _ \
| | | |>  | (_) | | | | \__/| (_) | | |  __/
\_| |_/_/\_\___/|_| |_|\____/\___/|_|  \___|
 
VERSION: 2.0.1
 
[ 23h00m47s ] - [ INFO  ] => Selected Logger: Default Logger.
[ 23h00m47s ] - [NOTICE ] => Logger ready.
[ 23h00m47s ] - [ INFO  ] => Selected Library Interface: ERIS.
[ 23h00m47s ] - [NOTICE ] => Library Interface ready. [TYPE: 0]
/home/kike/prs/discord/dead-master/node_modules/axoncore/src/Libraries/eris/lib/ErisClient.js:1
TypeError: this.client.executeWebhook is not a function
    at ErisClient.triggerWebhook (/home/kike/prs/discord/dead-master/node_modules/axoncore/src/Libraries/eris/lib/ErisClient.js:80:27)
    at AxonUtils.triggerWebhook (/home/kike/prs/discord/dead-master/node_modules/axoncore/src/Utility/AxonUtils.js:129:33)
    at Client.log (/home/kike/prs/discord/dead-master/node_modules/axoncore/src/AxonClient.js:442:28)
    at new AxonClient (/home/kike/prs/discord/dead-master/node_modules/axoncore/src/AxonClient.js:168:14)
    at new Client (/home/kike/prs/discord/dead-master/src/Client.js:19:5)
    at Object.<anonymous> (/home/kike/prs/discord/dead-master/src/Bot.js:56:13)
    at Generator.next (<anonymous>)
    at Object.<anonymous> (/home/kike/prs/discord/dead-master/src/index.js:1)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by bsian03** [comment]
Thanks, having a look

**Comment by bsian03** [comment]
Can you paste the contents of your Bot.js here?

**Comment by Khaaz** [comment]
Can you please also specify your:
- node version
- eris version (since it appears it's the library you are using)

**Comment by enbermudas** [comment]
Hi, I'm that guy from the question.

Node: v12.4.0

Also, I am not using Eris (that's a weird thing). I selected discord.js as the library in the creation of the projecy by using:

```bash
yarn create axoncore-app --lib discordjs --type esm dead-master
```

Discord.js: ^12.0.1

**Comment by Khaaz** [comment]
Maybe that's where the error is from (incorrect library selection). I'll have a look right now and I'll come back to you.
If you want, you can join our support server [here](discord.gg/QZ6B5US), it might be easier to discuss.

**Comment by Khaaz** [comment]
I think I identified the error.
Can you check you `config.json` file. And change the `"settings"` section with
```js
"settings": {
        "lang": "english",
        "debugMode": true,
        "library": 1,
        "logger": 0,
        "db": 1,
        "guildConfigCache": 1000
    },
```

**Comment by enbermudas** [comment]
That configuration solved that problem, but there is something new at the console:

```
[ 11h04m54s ] - [ ERROR ] => [TriggerWebhook] Webhook issue
DiscordAPIError: Invalid Form Body
webhook_id: Value "ID" is not snowflake.
[ 11h04m55s ] - [ ERROR ] => Error [DISALLOWED_INTENTS]: Privileged intent provided is not enabled or whitelisted.
    at WebSocketManager.createShards (/home/kike/prs/discord/dead-master/node_modules/discord.js/src/client/websocket/WebSocketManager.js:260:15)
```

**Comment by bsian03** [comment]
First one, you didn't set any webhooks, hence why you are getting those errors. Head to `secret.json` and set a webhook in each of the webhoooks properties
The second one is a result of you using priviledged intents, you can temporarily enable them in your application settings, though you won't be able to use them after the Discord grace period is over, in that case you will need to reconfigure your intents

**Comment by Khaaz** [comment]
For the record, it's due to an error withing `create-axoncore-app` that had incorrect default for settings.
I am currently working on fixing it.

**Comment by Khaaz** [comment]
> First one, you didn't set any webhooks, hence why you are getting those errors. Head to `secret.json` and set a webhook in each of the webhoooks properties
To complete what Bsian is saying, you can either have no value at all for said webhook (empty string) or a valid ID. It seems that you have an incorrect value (`ID`) which will cause Discord to error.

**Comment by bsian03** [comment]
invalid*

**Comment by enbermudas** [comment]
That was it! Thanks a lot and sorry for all those problems. Now it works just fine!

**Comment by Khaaz** [comment]
Happy to hear that!
If you have further issue, don't mind joining our support server as I stated above.

I'll reference this issue in my fix in create-axoncore-app and close this issue. Thanks for the report.
